name: ci/github-actions

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: nuget/setup-nuget@v1
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Clean
      uses: cake-build/cake-action@v1
      with:
        script-path: .build/build.cake
        target: Clean
    - name: Restore
      uses: cake-build/cake-action@v1
      with:
        script-path: .build/build.cake
        target: Restore
    - name: Build Libs
      uses: cake-build/cake-action@v1
      with:
        script-path: .build/build.cake
        target: BuildLibs
    - name: Build Clients
      uses: cake-build/cake-action@v1
      with:
        script-path: .build/build.cake
        target: BuildClients
    - name: Builds Tests
      uses: cake-build/cake-action@v1
      with:
        script-path: .build/build.cake
        target: BuildTests
    - name: Run Tests
      uses: cake-build/cake-action@v1
      with:
        script-path: .build/build.cake
        target: RunTests
    - name: Generate nuget package (Vanilla)
      run: nuget pack .build/Plugin.BLE.nuspec -Version $(git describe)
    - name: Generate nuget package (MvvmCross)
      run: nuget pack .build/MvvmCross.Plugin.BLE.nuspec -Version $(git describe)
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: ./*Plugin.BLE*.nupkg
